name: Release assets

on:
  push:
    branches:    
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
          fetch-depth: '0'
      - name: Put tag
        run: |
             checksum=`cat configs/assets_checksum`
             echo "Checksum: ${checksum}"
             if ! [ $(git tag -l "$checksum") ]; then
               echo "Release of this checksum not exist!"
               tar -czf assets.tar.gz assets
               git tag "${checksum}"
               git push origin --tags
               echo "TAG_NAME=${checksum}" >> "$GITHUB_ENV"
             fi
      - name: Release assets
        if: env.TAG_NAME
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.TAG_NAME }}
          artifacts: assets.tar.gz
      - name: Update UAV Server
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.SERVER_DISPATCH_TOKEN }}
          script: |
            const result = await github.rest.repos.createDispatchEvent({
              owner: context.repo.owner,
              repo: 'UAV_server',
              event_type: 'dependency_update'
            })
            console.log(result);
